"""add_tested_vector_dimension

Revision ID: ba3fc7114bef
Revises: d42e50473c55
Create Date: 2026-08-10 10:42:35.230349
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ba3fc7114bef"
down_revision: str | None = "d42e50473c55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用本次 Schema 变更。"""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tested_vector_dimension", sa.Integer(), nullable=True))
        batch_op.create_check_constraint(
            "ck_model_configs_tested_vector_dimension",
            "tested_vector_dimension IS NULL OR tested_vector_dimension > 0",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """回退本次 Schema 变更。"""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_configs", schema=None) as batch_op:
        batch_op.drop_constraint("ck_model_configs_tested_vector_dimension", type_="check")
        batch_op.drop_column("tested_vector_dimension")

    # ### end Alembic commands ###
