"""initial_schema

Revision ID: d42e50473c55
Revises:
Create Date: 2026-08-09 23:08:10.024689
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

revision: str = "d42e50473c55"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用本次 Schema 变更。"""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_tasks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("task_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("scope_id", sa.Text(), nullable=True),
        sa.Column("target_version", sa.Integer(), nullable=True),
        sa.Column("progress_current", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("progress_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name="ck_background_tasks_status",
        ),
        sa.CheckConstraint(
            "task_type IN ('memory_consolidation', 'index_rebuild', 'vector_cleanup')",
            name="ck_background_tasks_type",
        ),
        sa.CheckConstraint("progress_current >= 0", name="ck_background_tasks_current"),
        sa.CheckConstraint("progress_total >= 0", name="ck_background_tasks_total"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("background_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ux_active_index_rebuild",
            ["task_type"],
            unique=True,
            sqlite_where=sa.text(
                "task_type = 'index_rebuild' AND status IN ('pending', 'running')"
            ),
        )
        batch_op.create_index(
            "ux_memory_task_target",
            ["task_type", "scope_id", "target_version"],
            unique=True,
            sqlite_where=sa.text("task_type = 'memory_consolidation'"),
        )

    op.create_table(
        "characters",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("introduction", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("system_prompt", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column(
            "dialogue_examples_json", sa.Text(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.create_index("ix_characters_updated_at", ["updated_at"], unique=False)

    op.create_table(
        "model_configs",
        sa.Column("group_name", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("model_name", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("secret_ref", sa.Text(), nullable=True),
        sa.Column("key_tail", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("vector_dimension", sa.Integer(), nullable=True),
        sa.Column("config_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tested_fingerprint", sa.Text(), nullable=True),
        sa.Column("tested_at", sa.Text(), nullable=True),
        sa.Column("rebuild_required", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint("group_name IN ('main', 'embed')", name="ck_model_configs_group"),
        sa.CheckConstraint("config_version >= 0", name="ck_model_configs_version"),
        sa.CheckConstraint("rebuild_required IN (0, 1)", name="ck_model_configs_rebuild"),
        sa.CheckConstraint(
            "vector_dimension IS NULL OR vector_dimension > 0",
            name="ck_model_configs_vector_dimension",
        ),
        sa.PrimaryKeyConstraint("group_name"),
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("singleton_key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("persona_name", sa.Text(), nullable=False),
        sa.Column("bio", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint("singleton_key = 'current'", name="ck_user_identities_singleton_key"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("singleton_key"),
    )
    op.create_table(
        "world_books",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("raw_content", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "long_term_memories",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("character_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source_label", sa.Text(), nullable=False),
        sa.Column("memory_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("index_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("embedding_version", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("last_index_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "index_status IN ('pending', 'ready', 'stale', 'failed')",
            name="ck_long_term_memories_index_status",
        ),
        sa.CheckConstraint("status IN ('active', 'invalid')", name="ck_long_term_memories_status"),
        sa.CheckConstraint(
            "type IN ('用户偏好', '角色承诺', '关系变化', '重要剧情', '长期目标')",
            name="ck_long_term_memories_type",
        ),
        sa.CheckConstraint("importance BETWEEN 1 AND 5", name="ck_long_term_memories_importance"),
        sa.CheckConstraint("memory_version >= 1", name="ck_long_term_memories_version"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("long_term_memories", schema=None) as batch_op:
        batch_op.create_index(
            "ix_memories_character_status",
            ["character_id", "status", "type", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_memories_index_status", ["index_status", "embedding_version"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("character_id", sa.Text(), nullable=False),
        sa.Column("world_book_id", sa.Text(), nullable=True),
        sa.Column("round_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("consolidated_round", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("summary", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "consolidated_round <= round_count", name="ck_sessions_consolidated_not_ahead"
        ),
        sa.CheckConstraint("consolidated_round >= 0", name="ck_sessions_consolidated_round"),
        sa.CheckConstraint("round_count >= 0", name="ck_sessions_round_count"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["world_book_id"], ["world_books.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_character", ["character_id", "updated_at"], unique=False)
        batch_op.create_index("ix_sessions_updated_at", ["updated_at"], unique=False)
        batch_op.create_index("ix_sessions_world_book", ["world_book_id"], unique=False)

    op.create_table(
        "world_book_entries",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("world_book_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("keywords_json", sa.Text(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("category", sa.Text(), server_default=sa.text("'未分类'"), nullable=False),
        sa.Column("resident", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("enabled", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("index_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("embedding_version", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("last_index_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "index_status IN ('pending', 'ready', 'stale', 'failed')",
            name="ck_world_book_entries_index_status",
        ),
        sa.CheckConstraint("enabled IN (0, 1)", name="ck_world_book_entries_enabled"),
        sa.CheckConstraint("resident IN (0, 1)", name="ck_world_book_entries_resident"),
        sa.ForeignKeyConstraint(["world_book_id"], ["world_books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("world_book_entries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_world_book_entries_index_status",
            ["index_status", "embedding_version"],
            unique=False,
        )
        batch_op.create_index(
            "ix_world_book_entries_lookup",
            ["world_book_id", "enabled", "resident", "position"],
            unique=False,
        )
        batch_op.create_index(
            "ux_world_book_entries_position", ["world_book_id", "position"], unique=True
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("retrieved_entries_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "retrieved_entries_json IS NULL OR role = 'assistant'",
            name="ck_messages_retrieved_only_assistant",
        ),
        sa.CheckConstraint("role IN ('user', 'assistant', 'memo')", name="ck_messages_role"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_session_created", ["session_id", "created_at", "position"], unique=False
        )
        batch_op.create_index("ux_messages_position", ["session_id", "position"], unique=True)

    op.create_table(
        "session_context_snapshots",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("identity_source_id", sa.Text(), nullable=False),
        sa.Column("identity_name", sa.Text(), nullable=False),
        sa.Column("identity_persona_name", sa.Text(), nullable=False),
        sa.Column("identity_bio", sa.Text(), nullable=False),
        sa.Column("character_source_id", sa.Text(), nullable=False),
        sa.Column("character_name", sa.Text(), nullable=False),
        sa.Column("character_introduction", sa.Text(), nullable=False),
        sa.Column("character_system_prompt", sa.Text(), nullable=False),
        sa.Column("character_dialogue_examples_json", sa.Text(), nullable=False),
        sa.Column("world_book_source_id", sa.Text(), nullable=True),
        sa.Column("world_book_name", sa.Text(), nullable=True),
        sa.Column("world_book_raw_content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "memory_sources",
        sa.Column("memory_id", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("source_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(["memory_id"], ["long_term_memories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("memory_id", "message_id"),
    )
    op.create_table(
        "message_blocks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.CheckConstraint("type IN ('action', 'dialogue')", name="ck_message_blocks_type"),
        sa.CheckConstraint("sequence >= 0", name="ck_message_blocks_sequence"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message_blocks", schema=None) as batch_op:
        batch_op.create_index("ux_message_blocks_sequence", ["message_id", "sequence"], unique=True)

    op.create_table(
        "session_world_book_entry_snapshots",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("context_snapshot_id", sa.Text(), nullable=False),
        sa.Column("source_entry_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("keywords_json", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("resident", sa.Integer(), nullable=False),
        sa.Column("index_status", sa.Text(), nullable=False),
        sa.Column("embedding_version", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("last_index_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "index_status IN ('pending', 'ready', 'stale', 'failed')",
            name="ck_session_entry_snapshots_index_status",
        ),
        sa.CheckConstraint("resident IN (0, 1)", name="ck_session_entry_snapshots_resident"),
        sa.ForeignKeyConstraint(
            ["context_snapshot_id"], ["session_context_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_world_book_entry_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_session_entry_snapshot_lookup",
            ["context_snapshot_id", "resident", "position"],
            unique=False,
        )
        batch_op.create_index(
            "ux_session_entry_snapshot_source",
            ["context_snapshot_id", "source_entry_id"],
            unique=True,
        )

    # 初始数据只建立可用的单用户身份与两类空模型配置，不混入演示业务数据。
    timestamp = datetime.now(UTC).isoformat(timespec="milliseconds").replace("+00:00", "Z")
    identity_table = sa.table(
        "user_identities",
        sa.column("id", sa.Text()),
        sa.column("singleton_key", sa.Text()),
        sa.column("name", sa.Text()),
        sa.column("persona_name", sa.Text()),
        sa.column("bio", sa.Text()),
        sa.column("created_at", sa.Text()),
        sa.column("updated_at", sa.Text()),
    )
    op.bulk_insert(
        identity_table,
        [
            {
                "id": "00000000-0000-4000-8000-000000000001",
                "singleton_key": "current",
                "name": "用户",
                "persona_name": "默认身份",
                "bio": "",
                "created_at": timestamp,
                "updated_at": timestamp,
            }
        ],
    )
    model_config_table = sa.table(
        "model_configs",
        sa.column("group_name", sa.Text()),
        sa.column("base_url", sa.Text()),
        sa.column("model_name", sa.Text()),
        sa.column("key_tail", sa.Text()),
        sa.column("config_version", sa.Integer()),
        sa.column("rebuild_required", sa.Integer()),
        sa.column("updated_at", sa.Text()),
    )
    op.bulk_insert(
        model_config_table,
        [
            {
                "group_name": group_name,
                "base_url": "",
                "model_name": "",
                "key_tail": "",
                "config_version": 0,
                "rebuild_required": 0,
                "updated_at": timestamp,
            }
            for group_name in ("main", "embed")
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """回退本次 Schema 变更。"""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_world_book_entry_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ux_session_entry_snapshot_source")
        batch_op.drop_index("ix_session_entry_snapshot_lookup")

    op.drop_table("session_world_book_entry_snapshots")
    with op.batch_alter_table("message_blocks", schema=None) as batch_op:
        batch_op.drop_index("ux_message_blocks_sequence")

    op.drop_table("message_blocks")
    op.drop_table("memory_sources")
    op.drop_table("session_context_snapshots")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ux_messages_position")
        batch_op.drop_index("ix_messages_session_created")

    op.drop_table("messages")
    with op.batch_alter_table("world_book_entries", schema=None) as batch_op:
        batch_op.drop_index("ux_world_book_entries_position")
        batch_op.drop_index("ix_world_book_entries_lookup")
        batch_op.drop_index("ix_world_book_entries_index_status")

    op.drop_table("world_book_entries")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_world_book")
        batch_op.drop_index("ix_sessions_updated_at")
        batch_op.drop_index("ix_sessions_character")

    op.drop_table("sessions")
    with op.batch_alter_table("long_term_memories", schema=None) as batch_op:
        batch_op.drop_index("ix_memories_index_status")
        batch_op.drop_index("ix_memories_character_status")

    op.drop_table("long_term_memories")
    op.drop_table("world_books")
    op.drop_table("user_identities")
    op.drop_table("model_configs")
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index("ix_characters_updated_at")

    op.drop_table("characters")
    with op.batch_alter_table("background_tasks", schema=None) as batch_op:
        batch_op.drop_index(
            "ux_memory_task_target", sqlite_where=sa.text("task_type = 'memory_consolidation'")
        )
        batch_op.drop_index(
            "ux_active_index_rebuild",
            sqlite_where=sa.text(
                "task_type = 'index_rebuild' AND status IN ('pending', 'running')"
            ),
        )

    op.drop_table("background_tasks")
    # ### end Alembic commands ###
